#!/bin/bash
alias ':q'=exit
alias 'x'=exit		
alias 'q'=exit		
alias lsa='ls -ahF'
alias lsl='ls -lhF'
alias a='sudo apt-get'
alias s='apt-cache search'
alias xc='nyxmms2'
alias lsls="lsl -S"
alias n="notify"
alias idf=gnomevfs-info
alias '..'='cd ..'
alias '....'='cd ../..'
alias '~'='cd ~'
alias sshproxy='ssh -CfNg ofan@shell.cjb.net 127.0.0.1:1080'
alias cls=clear
alias lsal='lsa -l'
alias lsla='lsal'
alias 'gbk2utf8'='iconv -fgbk -tutf8'
alias g2u=gbk2utf8
alias du='du -h'
alias df='df -h'
alias echoe='echo -e'
alias y=yaourt
alias n=notify
alias hex='od -Ax -tx1z -v'
alias 'gentag'='ctags -R --c++-kinds=+px --fields=+iaS --extra=+q .'
alias b='sudo bauerbill'
alias ba='b --aur'
alias bau='ba -Syu'
alias bas='ba -Ss'
alias bai='ba -S'
alias baq='ba -Qsi'
alias bal='ba -Ql'
alias bao='ba -Qo'
alias bar='ba -R'
alias rot13="tr a-zA-Z n-za-mN-ZA-M"
alias c='clyde'
alias ktl='kubectl'
alias k='kubectl'
