#!/bin/zsh
autoload colors zsh/terminfo
if [[ "$terminfo[colors]" -ge 8 ]]; then
    colors
fi
for color in RED GREEN YELLOW BLUE MAGENTA CYAN WHITE; do
    eval PR_$color='%{$terminfo[bold]$fg[${(L)color}]%}'
    eval PR_LIGHT_$color='%{$fg[${(L)color}]%}'
    (( count = $count + 1 ))
done

count=0
for color in RED GREEN YELLOW BLUE MAGENTA CYAN WHITE; do
    eval TC_$color='$terminfo[bold]$fg[${(L)color}]'
    eval TC_LIGHT_$color='$fg[${(L)color}]'
    (( count = $count + 1 ))
done

PR_NO_COLOR="%{$terminfo[sgr0]%}"
TC_NO_COLOR="$terminfo[sgr0]"
