#!/bin/zsh
_shell=$(basename $SHELL)
if type mise &> /dev/null; then
    eval "$(mise completion $_shell)"
fi

if type kubectl &> /dev/null; then
    source <(kubectl completion $_shell)
fi

if type helm &> /dev/null; then
    source <(helm completion $_shell)
fi

if type yq &> /dev/null; then
    source <(yq shell-completion $_shell)
fi
