#!/bin/sh
# Path: .profile.d/02-brew-rtx

# install brew if not installed yet (https://brew.sh/) 

test -d ~/.linuxbrew && eval "$(~/.linuxbrew/bin/brew shellenv)"
test -d /home/linuxbrew/.linuxbrew && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

if ! type brew &> /dev/null; then
    echo Installing brew at $0:A:$LINENO
    curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
fi

# install rtx if not installed yet
if ! type rtx &> /dev/null; then
    brew install rtx
fi

if type rtx &> /dev/null; then
    echo Loading rtx at $0:A:$LINENO
    if [ -n "$BASH_VERSION" ]; then
        SHELL=bash
    elif [ -n "$ZSH_VERSION" ]; then
        SHELL=zsh
    fi
    eval "$(rtx activate $SHELL)"
fi