#!/bin/sh
local _shell=$(basename $SHELL)

local _cmd_list=(
    mise
    kustomize
    velero
    helm
    argocd
    kubectl
    talosctl
    yq
    krew
)

for _cmd in $_cmd_list; do
    [[ -n "$_DEBUG" ]] && echo "Enable auto-completion for cmd $_cmd"
    cached completion $_cmd completion $_shell &!
done

